spring:
  profiles:
    active: dev

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  config: classpath:logback-spring.xml

management:
  endpoint:
    web:
      exposure:
        include: health, info, metrics, loggers