spring:
  application:
    name: discodeit
  profiles:
    active: prod

discodeit:
  storage:
    type: local
    local:
      root-path: ./upload

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1