spring:
  application:
    name: discodeit
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: always

discodeit:
  storage:
    type: local
    local:
      root-path: ./upload

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1

logging:
  level:
    root: info