spring:
  application:
    name: discodeit

discodeit:
  repository:
    type: file
    file-directory: \src\main\resources\dir\

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1

#logging:
#  level:
#    root: INFO
#    org.springframework: INFO
#    org.springframework.web: DEBUG